### ISSUE TITLE
Drastic shortening of relation URIs

### ISSUE THREAD

**Issue by brodecva** [odalic/odalic-ui#75] opened 2016-09-05 22:17 UTC
I used latest server version and configuration and our old friends Books.csv.
Sorry I did not notice it sooner, I tend to overlook these things.
I know labels can be pretty long, but this kind of shortening does not help much. The labels are not intelligible: https://drive.google.com/file/d/0B7AckGrBKzUtNjI2THVjeHlQTk0/view?usp=sharing .

**Comment by brodecva** [comment] 2016-09-05 22:34
Seems that server does not return any labels. I will assign a separate issue to @JanVana  to investigate if the ontology concepts really lack labels.

**Comment by istvan-satmari** [comment] 2016-09-06 06:05
Did that, though could not test the result (not enough time today).
If problems arise and I'm not available, do this:
- src/directives/graphvis/graphvis.js, line 201:
concept = text.dotted(resource, 25 /* this number here is important - how many characters? */); 
- src/directives/graphvis/label.js
 - line 253: if (dist < 18*15 /* at which edge length should the label be abbreviated to  'dotted' text? */) 
 - line 259: changeTextNS(text.dotted(_btext, 20 /* to what amount of character to shorten, including dots and 'arrows'  << and whitespaces  */));

**Comment by brodecva** [comment] 2016-09-06 12:17
> If problems arise and I'm not available, do this:

Well, the fix made the labels completely invisible.  Luckily I hope I temporarily fixed it by guessing that you also have to extend the linksDistance. Please smooth it out as soon as you get some free time. Thanks!

**Comment by istvan-satmari** [comment] 2016-09-06 15:15
It seems there is some misunderstanding: there are only 3 states for a label:
- if it fits, the whole label (if a specific label is provided by server, then it is used; if not, the URI is parsed and using heuristics certain parts are displayed - domain + concept; if even that does not help, the URI is automatically shortened to 25 characters: that's the line 201 in graphvis.js)
- it an edge is slightly shorter, so the whole corresponding label does not fit, it is shortened (to 20 characters - that's the line 259 in label.js)
- if not even 20 characters fit,  the label is hidden
So, yeah, extending the linksDistance may be the only option.
Since I could not reproduce the issue on my PC, I would like to ask for a sample result, if possible...? Thanks.

**Comment by tomas-knap** [comment] 2016-09-06 15:20
Yes, there are no labels, must be fixed. Thanks!

**Comment by istvan-satmari** [comment] 2016-09-06 15:58
nvm, I made the shortening dynamic. Not the most optimized code, though, it should work. There are no problems on my PC now, so I close the issue.
If you still, for some reason, don't see labels, please, provide screenshot + ideally a result, or a part of it. (i.e. an URI which causes the problems).

**Closed** 2016-09-06 15:59 UTC
Labels: bug, graphics, priority: High, ui
