### ISSUE TITLE
Solve the issues with namespaces when proposing relations

### ISSUE THREAD

**Issue by tomas-knap** [odalic/odalic-ui#174] opened 2016-11-30 15:48 UTC
Currently, the prefixes for relations are defined as: 

![screen shot 2016-11-30 at 16 45 19](https://cloud.githubusercontent.com/assets/3014917/20759181/73e4f078-b71c-11e6-8a3c-fa5617dde685.png)

So the name of the KB is used (hardcoded?)

This has to be improved. Ideally in a way that there are namespace prefixes (in the config file somewhere - could be general config file or per KB config file), which are respected - so certain URI prefix (for which there is abbreviation) is found, such abbreviation is used.

**Comment by brodecva** [comment] 2016-12-01 17:29
This could be generalized to all resources, not only properties describing the relations.

I suggest the following: first I will extend the methods of the class that we use for resources by adding methods like getPrefixedUri(), getUriPrefix(), getUriSuffix(). These should cover the needed use cases. Of course the prefix might be left undefined for a resource, in such case these would return null or other suitable default value.

Then I will either assign the issue to @JanVana  or @josef-janousek to fill the resource instances at appropriate time with the prefixes read from a configuration file.

**Comment by tomas-knap** [comment] 2016-12-02 14:03
Yes, this applies to all resources.

**Comment by brodecva** [comment] 2017-01-13 12:32
Waits for https://github.com/odalic/sti/issues/171 .

**Comment by brodecva** [comment] 2017-01-19 00:48
Duplicate of #92 .

**Comment by brodecva** [comment] 2017-01-19 00:49
The server is ready BTW and provides all the info needed.

**Closed** 2017-01-19 00:48 UTC
Labels: api, classification, disambiguation, duplicate, enhancement, extension, java, knowledge bases, relations
