### ISSUE TITLE
Unify the fonts across titles

### ISSUE THREAD

**Issue by brodecva** [odalic/odalic-ui#235] opened 2017-01-06 12:27 UTC

**Comment by tomas-knap** [comment] 2017-01-06 20:01
@istvan-satmari mentioned that this was caused by some of the latest commits (5.1.). Please discuss with Istvan how to solve that, he looked like having some ideas how to solve that ;)

**Comment by istvan-satmari** [comment] 2017-01-18 09:59
since I am not responsible for the bug (this worked before the corresponding commit), assigning to @KataBoku

**Comment by tomas-knap** [comment] 2017-02-08 10:32
@brodecva Please provide particular examples of wrong fonts, so that it is easier for @KataBoku

**Comment by tomas-knap** [comment] 2017-02-14 08:29
@KataBoku So is it ready for test?

**Closed** 2017-02-16 15:47 UTC
Labels: bug, css, in progress, ui
