### ISSUE TITLE
UI: Same icon for two actions

### ISSUE THREAD

**Issue by tomas-knap** [odalic/odalic-ui#145] opened 2016-11-18 13:42 UTC
There are the same icons for "propose" and "detail", which is really confusing.

![screen shot 2016-11-18 at 14 41 56](https://cloud.githubusercontent.com/assets/3014917/20431946/370e1a18-ad9d-11e6-80a3-7dcca89caa26.png)

Please select different icons.

**Comment by brodecva** [comment] 2016-11-18 13:56
Duplicate of #139. Still I cannot explain why I let such a simple, yet relatively prominent bug pass to 4th iteration. This can be fixed ASAP. Closing this one.

**Closed** 2016-11-18 13:56 UTC
Labels: bug, duplicate, priority: High
