### ISSUE TITLE
UI: Propose - do not send alerts, but display notifications

### ISSUE THREAD

**Issue by tomas-knap** [odalic/odalic-ui#154] opened 2016-11-18 14:49 UTC
When clicking OK in propose dialog, do not send alerts, just display message with green background when everything is ok and message with red background when there was an error. 

Alerts should not be use at all, they are not bounded to any dialog and may appear several times etc.

**Comment by brodecva** [comment] 2016-11-18 15:48
Duplicate of #132. Closing.

**Closed by brodecva** 2016-11-18 15:48 UTC
Labels: enhancement
