### ISSUE TITLE
Statistical data dialog not properly initialized!

### ISSUE THREAD

**Issue by tomas-knap** [odalic/odalic-ui#342] opened 2017-02-15 10:14 UTC
Steps:
Run statistical task on top of 
[STMK_2012_LIVEBIRTHS-10lines.csv.zip](https://github.com/odalic/odalic-ui/files/776675/STMK_2012_LIVEBIRTHS-10lines.csv.zip) and dbpedia (JAN)

Adjust the dimensions and measures, e.g.:

![screen shot 2017-02-15 at 11 06 54](https://cloud.githubusercontent.com/assets/3014917/22969710/c673c7ee-f36f-11e6-8f81-e8dc0d81147a.png)

Reexecute
Open the task result, go to dimensions and measures
The dialog is empty!!
![screen shot 2017-02-15 at 11 08 16](https://cloud.githubusercontent.com/assets/3014917/22969701/bfa2ad40-f36f-11e6-9cfd-7e3c0c6af1a8.png)

When I try to export, the statistical data is there!

**Comment by tomas-knap** [comment] 2017-02-15 10:14
Maybe related with https://github.com/odalic/sti/issues/364

**Comment by brodecva** [comment] 2017-02-16 14:53
> Maybe related with odalic/sti#364

Yes, exactly the same problem there, @tomas-knap  . I will leave this issue open and not mark it as duplciate, because the odalic/sti#364 cause was identified to be a browser cache refresh, but this one is caused by a mere re-execution.

**Comment by brodecva** [comment] 2017-02-16 22:48
Closed by https://github.com/odalic/odalic-ui/pull/349 .

**Closed** 2017-02-16 22:48 UTC
Labels: bug, in progress, priority: Urgent
