### ISSUE TITLE
UI: Search - do not send alerts at all, they are send off context and multiple times!

### ISSUE THREAD

**Issue by tomas-knap** [odalic/odalic-ui#161] opened 2016-11-22 13:27 UTC
Search component - Do not send alerts at all - currently they are send when there is some issue. Nevertheless, they are send without respect of the dialog I work with - so when there is some problem during searching of e.g. concepts for certain Book in books1.csv and then if I e.g. switch to list of task configurations, it still throws that exceptions via alert windows (although they are not relevant!) And such alerts are thrown multiple times.

**Comment by tomas-knap** [comment] 2016-11-22 13:27
Follow-up of #154

**Comment by brodecva** [comment] 2016-11-24 17:27
> Follow-up of #154

Alright, but still a duplicate of #132. The assignment is clear: get rid of all alerts!

**Closed** 2016-11-24 17:27 UTC
Labels: bug, priority: High
